// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKzVylYD8i-Qn4CTmAR8iJVDtmUEnLkAM',
    appId: '1:11046090334:android:05ab03bddfa2f848e3a6cf',
    messagingSenderId: '11046090334',
    projectId: 'moneycycle-5f900',
    databaseURL:
        'https://moneycycle-5f900-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'moneycycle-5f900.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKGQrwIdOqiW86mzuXUQfO85G4m-mhf8E',
    appId: '1:11046090334:ios:d31ea4efe7d8fdaae3a6cf',
    messagingSenderId: '11046090334',
    projectId: 'moneycycle-5f900',
    databaseURL:
        'https://moneycycle-5f900-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'moneycycle-5f900.appspot.com',
    androidClientId:
        '11046090334-t5f5m0don9md8o67be7lcn7hcht31aa0.apps.googleusercontent.com',
    iosClientId:
        '11046090334-jnl1qlhau488i7g7e6pi57n3skdi9a5m.apps.googleusercontent.com',
    iosBundleId: 'com.storyDx.moneyCycle',
  );
}
